/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PairRouteImport } from './routes/pair'
import { Route as HackRouteImport } from './routes/hack'
import { Route as CodeRouteImport } from './routes/code'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as HackIndexRouteImport } from './routes/hack.index'
import { Route as CodeIndexRouteImport } from './routes/code.index'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsVpnRouteImport } from './routes/settings.vpn'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsArchivedPlansRouteImport } from './routes/settings.archived-plans'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as HackSessionIdRouteImport } from './routes/hack.$sessionId'
import { Route as ChatPlanRunnerRunIdRouteImport } from './routes/_chat.plan-runner.$runId'
import { Route as ChatDraftDraftIdRouteImport } from './routes/_chat.draft.$draftId'
import { Route as ChatEnvironmentIdThreadIdRouteImport } from './routes/_chat.$environmentId.$threadId'
import { Route as ChatPlanRunnerFeatureNameRunRouteImport } from './routes/_chat.plan-runner.$featureName.run'
import { Route as ChatPlanRunnerFeatureNameConfigureRouteImport } from './routes/_chat.plan-runner.$featureName.configure'
import { Route as ChatPlanRunnerFeatureNamePlanIdRouteImport } from './routes/_chat.plan-runner.$featureName.$planId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const HackRoute = HackRouteImport.update({
  id: '/hack',
  path: '/hack',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const HackIndexRoute = HackIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HackRoute,
} as any)
const CodeIndexRoute = CodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CodeRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsVpnRoute = SettingsVpnRouteImport.update({
  id: '/vpn',
  path: '/vpn',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedPlansRoute = SettingsArchivedPlansRouteImport.update({
  id: '/archived-plans',
  path: '/archived-plans',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const HackSessionIdRoute = HackSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => HackRoute,
} as any)
const ChatPlanRunnerRunIdRoute = ChatPlanRunnerRunIdRouteImport.update({
  id: '/plan-runner/$runId',
  path: '/plan-runner/$runId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatDraftDraftIdRoute = ChatDraftDraftIdRouteImport.update({
  id: '/draft/$draftId',
  path: '/draft/$draftId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatEnvironmentIdThreadIdRoute =
  ChatEnvironmentIdThreadIdRouteImport.update({
    id: '/$environmentId/$threadId',
    path: '/$environmentId/$threadId',
    getParentRoute: () => ChatRoute,
  } as any)
const ChatPlanRunnerFeatureNameRunRoute =
  ChatPlanRunnerFeatureNameRunRouteImport.update({
    id: '/plan-runner/$featureName/run',
    path: '/plan-runner/$featureName/run',
    getParentRoute: () => ChatRoute,
  } as any)
const ChatPlanRunnerFeatureNameConfigureRoute =
  ChatPlanRunnerFeatureNameConfigureRouteImport.update({
    id: '/plan-runner/$featureName/configure',
    path: '/plan-runner/$featureName/configure',
    getParentRoute: () => ChatRoute,
  } as any)
const ChatPlanRunnerFeatureNamePlanIdRoute =
  ChatPlanRunnerFeatureNamePlanIdRouteImport.update({
    id: '/plan-runner/$featureName/$planId',
    path: '/plan-runner/$featureName/$planId',
    getParentRoute: () => ChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/code': typeof CodeRouteWithChildren
  '/hack': typeof HackRouteWithChildren
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/hack/$sessionId': typeof HackSessionIdRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/archived-plans': typeof SettingsArchivedPlansRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/vpn': typeof SettingsVpnRoute
  '/code/': typeof CodeIndexRoute
  '/hack/': typeof HackIndexRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/plan-runner/$runId': typeof ChatPlanRunnerRunIdRoute
  '/plan-runner/$featureName/$planId': typeof ChatPlanRunnerFeatureNamePlanIdRoute
  '/plan-runner/$featureName/configure': typeof ChatPlanRunnerFeatureNameConfigureRoute
  '/plan-runner/$featureName/run': typeof ChatPlanRunnerFeatureNameRunRoute
}
export interface FileRoutesByTo {
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/hack/$sessionId': typeof HackSessionIdRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/archived-plans': typeof SettingsArchivedPlansRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/vpn': typeof SettingsVpnRoute
  '/': typeof ChatIndexRoute
  '/code': typeof CodeIndexRoute
  '/hack': typeof HackIndexRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/plan-runner/$runId': typeof ChatPlanRunnerRunIdRoute
  '/plan-runner/$featureName/$planId': typeof ChatPlanRunnerFeatureNamePlanIdRoute
  '/plan-runner/$featureName/configure': typeof ChatPlanRunnerFeatureNameConfigureRoute
  '/plan-runner/$featureName/run': typeof ChatPlanRunnerFeatureNameRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/code': typeof CodeRouteWithChildren
  '/hack': typeof HackRouteWithChildren
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/hack/$sessionId': typeof HackSessionIdRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/archived-plans': typeof SettingsArchivedPlansRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/vpn': typeof SettingsVpnRoute
  '/_chat/': typeof ChatIndexRoute
  '/code/': typeof CodeIndexRoute
  '/hack/': typeof HackIndexRoute
  '/_chat/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/_chat/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/_chat/plan-runner/$runId': typeof ChatPlanRunnerRunIdRoute
  '/_chat/plan-runner/$featureName/$planId': typeof ChatPlanRunnerFeatureNamePlanIdRoute
  '/_chat/plan-runner/$featureName/configure': typeof ChatPlanRunnerFeatureNameConfigureRoute
  '/_chat/plan-runner/$featureName/run': typeof ChatPlanRunnerFeatureNameRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/code'
    | '/hack'
    | '/pair'
    | '/settings'
    | '/hack/$sessionId'
    | '/settings/archived'
    | '/settings/archived-plans'
    | '/settings/connections'
    | '/settings/general'
    | '/settings/vpn'
    | '/code/'
    | '/hack/'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/plan-runner/$runId'
    | '/plan-runner/$featureName/$planId'
    | '/plan-runner/$featureName/configure'
    | '/plan-runner/$featureName/run'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/pair'
    | '/settings'
    | '/hack/$sessionId'
    | '/settings/archived'
    | '/settings/archived-plans'
    | '/settings/connections'
    | '/settings/general'
    | '/settings/vpn'
    | '/'
    | '/code'
    | '/hack'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/plan-runner/$runId'
    | '/plan-runner/$featureName/$planId'
    | '/plan-runner/$featureName/configure'
    | '/plan-runner/$featureName/run'
  id:
    | '__root__'
    | '/_chat'
    | '/code'
    | '/hack'
    | '/pair'
    | '/settings'
    | '/hack/$sessionId'
    | '/settings/archived'
    | '/settings/archived-plans'
    | '/settings/connections'
    | '/settings/general'
    | '/settings/vpn'
    | '/_chat/'
    | '/code/'
    | '/hack/'
    | '/_chat/$environmentId/$threadId'
    | '/_chat/draft/$draftId'
    | '/_chat/plan-runner/$runId'
    | '/_chat/plan-runner/$featureName/$planId'
    | '/_chat/plan-runner/$featureName/configure'
    | '/_chat/plan-runner/$featureName/run'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  CodeRoute: typeof CodeRouteWithChildren
  HackRoute: typeof HackRouteWithChildren
  PairRoute: typeof PairRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hack': {
      id: '/hack'
      path: '/hack'
      fullPath: '/hack'
      preLoaderRoute: typeof HackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code': {
      id: '/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hack/': {
      id: '/hack/'
      path: '/'
      fullPath: '/hack/'
      preLoaderRoute: typeof HackIndexRouteImport
      parentRoute: typeof HackRoute
    }
    '/code/': {
      id: '/code/'
      path: '/'
      fullPath: '/code/'
      preLoaderRoute: typeof CodeIndexRouteImport
      parentRoute: typeof CodeRoute
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/vpn': {
      id: '/settings/vpn'
      path: '/vpn'
      fullPath: '/settings/vpn'
      preLoaderRoute: typeof SettingsVpnRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived-plans': {
      id: '/settings/archived-plans'
      path: '/archived-plans'
      fullPath: '/settings/archived-plans'
      preLoaderRoute: typeof SettingsArchivedPlansRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/hack/$sessionId': {
      id: '/hack/$sessionId'
      path: '/$sessionId'
      fullPath: '/hack/$sessionId'
      preLoaderRoute: typeof HackSessionIdRouteImport
      parentRoute: typeof HackRoute
    }
    '/_chat/plan-runner/$runId': {
      id: '/_chat/plan-runner/$runId'
      path: '/plan-runner/$runId'
      fullPath: '/plan-runner/$runId'
      preLoaderRoute: typeof ChatPlanRunnerRunIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/draft/$draftId': {
      id: '/_chat/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/draft/$draftId'
      preLoaderRoute: typeof ChatDraftDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$environmentId/$threadId': {
      id: '/_chat/$environmentId/$threadId'
      path: '/$environmentId/$threadId'
      fullPath: '/$environmentId/$threadId'
      preLoaderRoute: typeof ChatEnvironmentIdThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/plan-runner/$featureName/run': {
      id: '/_chat/plan-runner/$featureName/run'
      path: '/plan-runner/$featureName/run'
      fullPath: '/plan-runner/$featureName/run'
      preLoaderRoute: typeof ChatPlanRunnerFeatureNameRunRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/plan-runner/$featureName/configure': {
      id: '/_chat/plan-runner/$featureName/configure'
      path: '/plan-runner/$featureName/configure'
      fullPath: '/plan-runner/$featureName/configure'
      preLoaderRoute: typeof ChatPlanRunnerFeatureNameConfigureRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/plan-runner/$featureName/$planId': {
      id: '/_chat/plan-runner/$featureName/$planId'
      path: '/plan-runner/$featureName/$planId'
      fullPath: '/plan-runner/$featureName/$planId'
      preLoaderRoute: typeof ChatPlanRunnerFeatureNamePlanIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
  ChatEnvironmentIdThreadIdRoute: typeof ChatEnvironmentIdThreadIdRoute
  ChatDraftDraftIdRoute: typeof ChatDraftDraftIdRoute
  ChatPlanRunnerRunIdRoute: typeof ChatPlanRunnerRunIdRoute
  ChatPlanRunnerFeatureNamePlanIdRoute: typeof ChatPlanRunnerFeatureNamePlanIdRoute
  ChatPlanRunnerFeatureNameConfigureRoute: typeof ChatPlanRunnerFeatureNameConfigureRoute
  ChatPlanRunnerFeatureNameRunRoute: typeof ChatPlanRunnerFeatureNameRunRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
  ChatEnvironmentIdThreadIdRoute: ChatEnvironmentIdThreadIdRoute,
  ChatDraftDraftIdRoute: ChatDraftDraftIdRoute,
  ChatPlanRunnerRunIdRoute: ChatPlanRunnerRunIdRoute,
  ChatPlanRunnerFeatureNamePlanIdRoute: ChatPlanRunnerFeatureNamePlanIdRoute,
  ChatPlanRunnerFeatureNameConfigureRoute:
    ChatPlanRunnerFeatureNameConfigureRoute,
  ChatPlanRunnerFeatureNameRunRoute: ChatPlanRunnerFeatureNameRunRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface CodeRouteChildren {
  CodeIndexRoute: typeof CodeIndexRoute
}

const CodeRouteChildren: CodeRouteChildren = {
  CodeIndexRoute: CodeIndexRoute,
}

const CodeRouteWithChildren = CodeRoute._addFileChildren(CodeRouteChildren)

interface HackRouteChildren {
  HackSessionIdRoute: typeof HackSessionIdRoute
  HackIndexRoute: typeof HackIndexRoute
}

const HackRouteChildren: HackRouteChildren = {
  HackSessionIdRoute: HackSessionIdRoute,
  HackIndexRoute: HackIndexRoute,
}

const HackRouteWithChildren = HackRoute._addFileChildren(HackRouteChildren)

interface SettingsRouteChildren {
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsArchivedPlansRoute: typeof SettingsArchivedPlansRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsVpnRoute: typeof SettingsVpnRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsArchivedPlansRoute: SettingsArchivedPlansRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsVpnRoute: SettingsVpnRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  CodeRoute: CodeRouteWithChildren,
  HackRoute: HackRouteWithChildren,
  PairRoute: PairRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
