/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RemoteHostRouteImport } from './routes/remote-host'
import { Route as PairRouteImport } from './routes/pair'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as RemoteHostIndexRouteImport } from './routes/remote-host.index'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsVpnRouteImport } from './routes/settings.vpn'
import { Route as SettingsSourceControlRouteImport } from './routes/settings.source-control'
import { Route as SettingsKeybindingsRouteImport } from './routes/settings.keybindings'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsDiagnosticsRouteImport } from './routes/settings.diagnostics'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsArchivedPlansRouteImport } from './routes/settings.archived-plans'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as RemoteHostHostIdRouteImport } from './routes/remote-host.$hostId'
import { Route as ChatGlobalTerminalRouteImport } from './routes/_chat.global-terminal'
import { Route as ChatGitdiffRouteImport } from './routes/_chat.gitdiff'
import { Route as ChatBrowserLabRouteImport } from './routes/_chat.browser-lab'
import { Route as ChatPlanRunnerRunIdRouteImport } from './routes/_chat.plan-runner.$runId'
import { Route as ChatDraftDraftIdRouteImport } from './routes/_chat.draft.$draftId'
import { Route as ChatEnvironmentIdThreadIdRouteImport } from './routes/_chat.$environmentId.$threadId'
import { Route as ChatPlanRunnerFeatureNameRunRouteImport } from './routes/_chat.plan-runner.$featureName.run'
import { Route as ChatPlanRunnerFeatureNameConfigureRouteImport } from './routes/_chat.plan-runner.$featureName.configure'
import { Route as ChatPlanRunnerFeatureNamePlanIdRouteImport } from './routes/_chat.plan-runner.$featureName.$planId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteHostRoute = RemoteHostRouteImport.update({
  id: '/remote-host',
  path: '/remote-host',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteHostIndexRoute = RemoteHostIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RemoteHostRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsVpnRoute = SettingsVpnRouteImport.update({
  id: '/vpn',
  path: '/vpn',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSourceControlRoute = SettingsSourceControlRouteImport.update({
  id: '/source-control',
  path: '/source-control',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsKeybindingsRoute = SettingsKeybindingsRouteImport.update({
  id: '/keybindings',
  path: '/keybindings',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDiagnosticsRoute = SettingsDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedPlansRoute = SettingsArchivedPlansRouteImport.update({
  id: '/archived-plans',
  path: '/archived-plans',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const RemoteHostHostIdRoute = RemoteHostHostIdRouteImport.update({
  id: '/$hostId',
  path: '/$hostId',
  getParentRoute: () => RemoteHostRoute,
} as any)
const ChatGlobalTerminalRoute = ChatGlobalTerminalRouteImport.update({
  id: '/global-terminal',
  path: '/global-terminal',
  getParentRoute: () => ChatRoute,
} as any)
const ChatGitdiffRoute = ChatGitdiffRouteImport.update({
  id: '/gitdiff',
  path: '/gitdiff',
  getParentRoute: () => ChatRoute,
} as any)
const ChatBrowserLabRoute = ChatBrowserLabRouteImport.update({
  id: '/browser-lab',
  path: '/browser-lab',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPlanRunnerRunIdRoute = ChatPlanRunnerRunIdRouteImport.update({
  id: '/plan-runner/$runId',
  path: '/plan-runner/$runId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatDraftDraftIdRoute = ChatDraftDraftIdRouteImport.update({
  id: '/draft/$draftId',
  path: '/draft/$draftId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatEnvironmentIdThreadIdRoute =
  ChatEnvironmentIdThreadIdRouteImport.update({
    id: '/$environmentId/$threadId',
    path: '/$environmentId/$threadId',
    getParentRoute: () => ChatRoute,
  } as any)
const ChatPlanRunnerFeatureNameRunRoute =
  ChatPlanRunnerFeatureNameRunRouteImport.update({
    id: '/plan-runner/$featureName/run',
    path: '/plan-runner/$featureName/run',
    getParentRoute: () => ChatRoute,
  } as any)
const ChatPlanRunnerFeatureNameConfigureRoute =
  ChatPlanRunnerFeatureNameConfigureRouteImport.update({
    id: '/plan-runner/$featureName/configure',
    path: '/plan-runner/$featureName/configure',
    getParentRoute: () => ChatRoute,
  } as any)
const ChatPlanRunnerFeatureNamePlanIdRoute =
  ChatPlanRunnerFeatureNamePlanIdRouteImport.update({
    id: '/plan-runner/$featureName/$planId',
    path: '/plan-runner/$featureName/$planId',
    getParentRoute: () => ChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/pair': typeof PairRoute
  '/remote-host': typeof RemoteHostRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/browser-lab': typeof ChatBrowserLabRoute
  '/gitdiff': typeof ChatGitdiffRoute
  '/global-terminal': typeof ChatGlobalTerminalRoute
  '/remote-host/$hostId': typeof RemoteHostHostIdRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/archived-plans': typeof SettingsArchivedPlansRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/vpn': typeof SettingsVpnRoute
  '/remote-host/': typeof RemoteHostIndexRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/plan-runner/$runId': typeof ChatPlanRunnerRunIdRoute
  '/plan-runner/$featureName/$planId': typeof ChatPlanRunnerFeatureNamePlanIdRoute
  '/plan-runner/$featureName/configure': typeof ChatPlanRunnerFeatureNameConfigureRoute
  '/plan-runner/$featureName/run': typeof ChatPlanRunnerFeatureNameRunRoute
}
export interface FileRoutesByTo {
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/browser-lab': typeof ChatBrowserLabRoute
  '/gitdiff': typeof ChatGitdiffRoute
  '/global-terminal': typeof ChatGlobalTerminalRoute
  '/remote-host/$hostId': typeof RemoteHostHostIdRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/archived-plans': typeof SettingsArchivedPlansRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/vpn': typeof SettingsVpnRoute
  '/': typeof ChatIndexRoute
  '/remote-host': typeof RemoteHostIndexRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/plan-runner/$runId': typeof ChatPlanRunnerRunIdRoute
  '/plan-runner/$featureName/$planId': typeof ChatPlanRunnerFeatureNamePlanIdRoute
  '/plan-runner/$featureName/configure': typeof ChatPlanRunnerFeatureNameConfigureRoute
  '/plan-runner/$featureName/run': typeof ChatPlanRunnerFeatureNameRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/pair': typeof PairRoute
  '/remote-host': typeof RemoteHostRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/_chat/browser-lab': typeof ChatBrowserLabRoute
  '/_chat/gitdiff': typeof ChatGitdiffRoute
  '/_chat/global-terminal': typeof ChatGlobalTerminalRoute
  '/remote-host/$hostId': typeof RemoteHostHostIdRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/archived-plans': typeof SettingsArchivedPlansRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/vpn': typeof SettingsVpnRoute
  '/_chat/': typeof ChatIndexRoute
  '/remote-host/': typeof RemoteHostIndexRoute
  '/_chat/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/_chat/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/_chat/plan-runner/$runId': typeof ChatPlanRunnerRunIdRoute
  '/_chat/plan-runner/$featureName/$planId': typeof ChatPlanRunnerFeatureNamePlanIdRoute
  '/_chat/plan-runner/$featureName/configure': typeof ChatPlanRunnerFeatureNameConfigureRoute
  '/_chat/plan-runner/$featureName/run': typeof ChatPlanRunnerFeatureNameRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pair'
    | '/remote-host'
    | '/settings'
    | '/browser-lab'
    | '/gitdiff'
    | '/global-terminal'
    | '/remote-host/$hostId'
    | '/settings/archived'
    | '/settings/archived-plans'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/keybindings'
    | '/settings/source-control'
    | '/settings/vpn'
    | '/remote-host/'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/plan-runner/$runId'
    | '/plan-runner/$featureName/$planId'
    | '/plan-runner/$featureName/configure'
    | '/plan-runner/$featureName/run'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/pair'
    | '/settings'
    | '/browser-lab'
    | '/gitdiff'
    | '/global-terminal'
    | '/remote-host/$hostId'
    | '/settings/archived'
    | '/settings/archived-plans'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/keybindings'
    | '/settings/source-control'
    | '/settings/vpn'
    | '/'
    | '/remote-host'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/plan-runner/$runId'
    | '/plan-runner/$featureName/$planId'
    | '/plan-runner/$featureName/configure'
    | '/plan-runner/$featureName/run'
  id:
    | '__root__'
    | '/_chat'
    | '/pair'
    | '/remote-host'
    | '/settings'
    | '/_chat/browser-lab'
    | '/_chat/gitdiff'
    | '/_chat/global-terminal'
    | '/remote-host/$hostId'
    | '/settings/archived'
    | '/settings/archived-plans'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/keybindings'
    | '/settings/source-control'
    | '/settings/vpn'
    | '/_chat/'
    | '/remote-host/'
    | '/_chat/$environmentId/$threadId'
    | '/_chat/draft/$draftId'
    | '/_chat/plan-runner/$runId'
    | '/_chat/plan-runner/$featureName/$planId'
    | '/_chat/plan-runner/$featureName/configure'
    | '/_chat/plan-runner/$featureName/run'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  PairRoute: typeof PairRoute
  RemoteHostRoute: typeof RemoteHostRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote-host': {
      id: '/remote-host'
      path: '/remote-host'
      fullPath: '/remote-host'
      preLoaderRoute: typeof RemoteHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote-host/': {
      id: '/remote-host/'
      path: '/'
      fullPath: '/remote-host/'
      preLoaderRoute: typeof RemoteHostIndexRouteImport
      parentRoute: typeof RemoteHostRoute
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/vpn': {
      id: '/settings/vpn'
      path: '/vpn'
      fullPath: '/settings/vpn'
      preLoaderRoute: typeof SettingsVpnRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/source-control': {
      id: '/settings/source-control'
      path: '/source-control'
      fullPath: '/settings/source-control'
      preLoaderRoute: typeof SettingsSourceControlRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/keybindings': {
      id: '/settings/keybindings'
      path: '/keybindings'
      fullPath: '/settings/keybindings'
      preLoaderRoute: typeof SettingsKeybindingsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/diagnostics': {
      id: '/settings/diagnostics'
      path: '/diagnostics'
      fullPath: '/settings/diagnostics'
      preLoaderRoute: typeof SettingsDiagnosticsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived-plans': {
      id: '/settings/archived-plans'
      path: '/archived-plans'
      fullPath: '/settings/archived-plans'
      preLoaderRoute: typeof SettingsArchivedPlansRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/remote-host/$hostId': {
      id: '/remote-host/$hostId'
      path: '/$hostId'
      fullPath: '/remote-host/$hostId'
      preLoaderRoute: typeof RemoteHostHostIdRouteImport
      parentRoute: typeof RemoteHostRoute
    }
    '/_chat/global-terminal': {
      id: '/_chat/global-terminal'
      path: '/global-terminal'
      fullPath: '/global-terminal'
      preLoaderRoute: typeof ChatGlobalTerminalRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/gitdiff': {
      id: '/_chat/gitdiff'
      path: '/gitdiff'
      fullPath: '/gitdiff'
      preLoaderRoute: typeof ChatGitdiffRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/browser-lab': {
      id: '/_chat/browser-lab'
      path: '/browser-lab'
      fullPath: '/browser-lab'
      preLoaderRoute: typeof ChatBrowserLabRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/plan-runner/$runId': {
      id: '/_chat/plan-runner/$runId'
      path: '/plan-runner/$runId'
      fullPath: '/plan-runner/$runId'
      preLoaderRoute: typeof ChatPlanRunnerRunIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/draft/$draftId': {
      id: '/_chat/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/draft/$draftId'
      preLoaderRoute: typeof ChatDraftDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$environmentId/$threadId': {
      id: '/_chat/$environmentId/$threadId'
      path: '/$environmentId/$threadId'
      fullPath: '/$environmentId/$threadId'
      preLoaderRoute: typeof ChatEnvironmentIdThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/plan-runner/$featureName/run': {
      id: '/_chat/plan-runner/$featureName/run'
      path: '/plan-runner/$featureName/run'
      fullPath: '/plan-runner/$featureName/run'
      preLoaderRoute: typeof ChatPlanRunnerFeatureNameRunRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/plan-runner/$featureName/configure': {
      id: '/_chat/plan-runner/$featureName/configure'
      path: '/plan-runner/$featureName/configure'
      fullPath: '/plan-runner/$featureName/configure'
      preLoaderRoute: typeof ChatPlanRunnerFeatureNameConfigureRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/plan-runner/$featureName/$planId': {
      id: '/_chat/plan-runner/$featureName/$planId'
      path: '/plan-runner/$featureName/$planId'
      fullPath: '/plan-runner/$featureName/$planId'
      preLoaderRoute: typeof ChatPlanRunnerFeatureNamePlanIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatBrowserLabRoute: typeof ChatBrowserLabRoute
  ChatGitdiffRoute: typeof ChatGitdiffRoute
  ChatGlobalTerminalRoute: typeof ChatGlobalTerminalRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ChatEnvironmentIdThreadIdRoute: typeof ChatEnvironmentIdThreadIdRoute
  ChatDraftDraftIdRoute: typeof ChatDraftDraftIdRoute
  ChatPlanRunnerRunIdRoute: typeof ChatPlanRunnerRunIdRoute
  ChatPlanRunnerFeatureNamePlanIdRoute: typeof ChatPlanRunnerFeatureNamePlanIdRoute
  ChatPlanRunnerFeatureNameConfigureRoute: typeof ChatPlanRunnerFeatureNameConfigureRoute
  ChatPlanRunnerFeatureNameRunRoute: typeof ChatPlanRunnerFeatureNameRunRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatBrowserLabRoute: ChatBrowserLabRoute,
  ChatGitdiffRoute: ChatGitdiffRoute,
  ChatGlobalTerminalRoute: ChatGlobalTerminalRoute,
  ChatIndexRoute: ChatIndexRoute,
  ChatEnvironmentIdThreadIdRoute: ChatEnvironmentIdThreadIdRoute,
  ChatDraftDraftIdRoute: ChatDraftDraftIdRoute,
  ChatPlanRunnerRunIdRoute: ChatPlanRunnerRunIdRoute,
  ChatPlanRunnerFeatureNamePlanIdRoute: ChatPlanRunnerFeatureNamePlanIdRoute,
  ChatPlanRunnerFeatureNameConfigureRoute:
    ChatPlanRunnerFeatureNameConfigureRoute,
  ChatPlanRunnerFeatureNameRunRoute: ChatPlanRunnerFeatureNameRunRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface RemoteHostRouteChildren {
  RemoteHostHostIdRoute: typeof RemoteHostHostIdRoute
  RemoteHostIndexRoute: typeof RemoteHostIndexRoute
}

const RemoteHostRouteChildren: RemoteHostRouteChildren = {
  RemoteHostHostIdRoute: RemoteHostHostIdRoute,
  RemoteHostIndexRoute: RemoteHostIndexRoute,
}

const RemoteHostRouteWithChildren = RemoteHostRoute._addFileChildren(
  RemoteHostRouteChildren,
)

interface SettingsRouteChildren {
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsArchivedPlansRoute: typeof SettingsArchivedPlansRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsDiagnosticsRoute: typeof SettingsDiagnosticsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsKeybindingsRoute: typeof SettingsKeybindingsRoute
  SettingsSourceControlRoute: typeof SettingsSourceControlRoute
  SettingsVpnRoute: typeof SettingsVpnRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsArchivedPlansRoute: SettingsArchivedPlansRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsDiagnosticsRoute: SettingsDiagnosticsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsKeybindingsRoute: SettingsKeybindingsRoute,
  SettingsSourceControlRoute: SettingsSourceControlRoute,
  SettingsVpnRoute: SettingsVpnRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  PairRoute: PairRoute,
  RemoteHostRoute: RemoteHostRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
