export const WS_METHODS = {
  // Project registry methods
  projectsList: "projects.list",
  projectsAdd: "projects.add",
  projectsRemove: "projects.remove",
  projectsListEntries: "projects.listEntries",
  projectsSearchEntries: "projects.searchEntries",
  projectsReadFile: "projects.readFile",
  projectsWriteFile: "projects.writeFile",
  projectsCreateFile: "projects.createFile",
  projectsCreateDirectory: "projects.createDirectory",
  projectsRemoveEntry: "projects.removeEntry",
  projectsMoveEntry: "projects.moveEntry",
  projectsCopyEntry: "projects.copyEntry",
  filesystemBrowse: "filesystem.browse",

  // Shell methods
  shellOpenInEditor: "shell.openInEditor",

  // Git methods
  vcsPull: "vcs.pull",
  vcsRefreshStatus: "vcs.refreshStatus",
  vcsListRefs: "vcs.listRefs",
  vcsCreateWorktree: "vcs.createWorktree",
  vcsRemoveWorktree: "vcs.removeWorktree",
  vcsCreateRef: "vcs.createRef",
  vcsSwitchRef: "vcs.switchRef",
  vcsInit: "vcs.init",
  gitRunStackedAction: "git.runStackedAction",
  gitResolvePullRequest: "git.resolvePullRequest",
  gitPreparePullRequestThread: "git.preparePullRequestThread",
  gitDiffListRepositories: "gitDiff.listRepositories",
  gitDiffLoadChangeSignature: "gitDiff.loadChangeSignature",
  gitDiffLoadFile: "gitDiff.loadFile",
  gitDiffLoadFileIndex: "gitDiff.loadFileIndex",
  gitDiffLoadActiveChangeRequestStackedFileIndex: "gitDiff.loadActiveChangeRequestStackedFileIndex",
  gitDiffLoadStackedFileIndex: "gitDiff.loadStackedFileIndex",
  gitDiffLoadHistory: "gitDiff.loadHistory",
  gitDiffLoadIgnoreLists: "gitDiff.loadIgnoreLists",
  gitDiffCreateIgnoreList: "gitDiff.createIgnoreList",
  gitDiffUpdateIgnoreList: "gitDiff.updateIgnoreList",
  gitDiffDeleteIgnoreList: "gitDiff.deleteIgnoreList",
  gitDiffLoadReviewNotes: "gitDiff.loadReviewNotes",
  gitDiffCreateReviewNote: "gitDiff.createReviewNote",
  gitDiffDeleteReviewNote: "gitDiff.deleteReviewNote",
  gitDiffUpdateReviewSession: "gitDiff.updateReviewSession",
  gitDiffLoadReviewSession: "gitDiff.loadReviewSession",
  gitDiffRequestReviewNavigation: "gitDiff.requestReviewNavigation",
  gitDiffStageWorktreeChanges: "gitDiff.stageWorktreeChanges",
  gitDiffUnstageStagedChanges: "gitDiff.unstageStagedChanges",
  gitDiffDiscardWorktreeChanges: "gitDiff.discardWorktreeChanges",
  gitDiffDiscardWorktreeHunk: "gitDiff.discardWorktreeHunk",
  gitDiffAmendStagedChanges: "gitDiff.amendStagedChanges",
  gitDiffRevertCommit: "gitDiff.revertCommit",
  gitDiffCherryPickCommit: "gitDiff.cherryPickCommit",
  gitDiffLoadOperation: "gitDiff.loadOperation",
  gitDiffContinueOperation: "gitDiff.continueOperation",
  gitDiffAbortOperation: "gitDiff.abortOperation",
  gitDiffLoadStashes: "gitDiff.loadStashes",
  gitDiffCreateStash: "gitDiff.createStash",
  gitDiffApplyStash: "gitDiff.applyStash",
  gitDiffPopStash: "gitDiff.popStash",
  gitDiffDropStash: "gitDiff.dropStash",
  gitDiffCloseChangeRequest: "gitDiff.closeChangeRequest",
  gitDiffMergeChangeRequest: "gitDiff.mergeChangeRequest",
  gitDiffLoadChangeRequestChecks: "gitDiff.loadChangeRequestChecks",
  gitDiffLoadChangeRequestReviewThreads: "gitDiff.loadChangeRequestReviewThreads",
  gitDiffCommentChangeRequestLines: "gitDiff.commentChangeRequestLines",
  gitDiffRevertChangeRequestLines: "gitDiff.revertChangeRequestLines",

  // Terminal methods
  terminalOpen: "terminal.open",
  terminalWrite: "terminal.write",
  terminalResize: "terminal.resize",
  terminalClear: "terminal.clear",
  terminalRestart: "terminal.restart",
  terminalClose: "terminal.close",

  // Server meta
  serverGetConfig: "server.getConfig",
  serverListProviderSkills: "server.listProviderSkills",
  serverRefreshProviders: "server.refreshProviders",
  serverUpdateProvider: "server.updateProvider",
  serverUpsertKeybinding: "server.upsertKeybinding",
  serverRemoveKeybinding: "server.removeKeybinding",
  serverGetTraceDiagnostics: "server.getTraceDiagnostics",
  serverGetProcessDiagnostics: "server.getProcessDiagnostics",
  serverGetProcessResourceHistory: "server.getProcessResourceHistory",
  serverSignalProcess: "server.signalProcess",
  serverGetSettings: "server.getSettings",
  serverUpdateSettings: "server.updateSettings",
  serverDiscoverSourceControl: "server.discoverSourceControl",
  serverGetGlobalActions: "server.getGlobalActions",
  serverCreateGlobalAction: "server.createGlobalAction",
  serverUpdateGlobalAction: "server.updateGlobalAction",
  serverDeleteGlobalAction: "server.deleteGlobalAction",

  // Streaming subscriptions
  subscribeVcsStatus: "subscribeVcsStatus",
  subscribeOrchestrationDomainEvents: "subscribeOrchestrationDomainEvents",
  subscribeTerminalEvents: "subscribeTerminalEvents",
  subscribeServerConfig: "subscribeServerConfig",
  subscribeServerLifecycle: "subscribeServerLifecycle",
  subscribeAuthAccess: "subscribeAuthAccess",
  subscribeLocalServers: "subscribeLocalServers",

  // Tmux manager
  terminalAttachTmux: "terminal.attachTmux",
  terminalDetachTmux: "terminal.detachTmux",
  terminalWriteTmux: "terminal.writeTmux",
  terminalResizeTmux: "terminal.resizeTmux",

  // Raw TCP Listener
  rawTcpCreateListener: "rawTcp.createListener",
  rawTcpStopListener: "rawTcp.stopListener",
  rawTcpListListeners: "rawTcp.listListeners",
  rawTcpListSessions: "rawTcp.listSessions",
  rawTcpSessionWrite: "rawTcp.sessionWrite",
  rawTcpSessionUpgradePty: "rawTcp.sessionUpgradePty",
  rawTcpSessionClose: "rawTcp.sessionClose",
  subscribeRawTcpEvents: "subscribeRawTcpEvents",

  // Remote Controller
  remoteControllerListHosts: "remoteController.listHosts",
  remoteControllerCreateHost: "remoteController.createHost",
  remoteControllerUpdateHost: "remoteController.updateHost",
  remoteControllerDeleteHost: "remoteController.deleteHost",
  remoteControllerStartConnection: "remoteController.startConnection",
  remoteControllerStopConnection: "remoteController.stopConnection",
  remoteControllerSetConnectionPath: "remoteController.setConnectionPath",
  remoteControllerListConnections: "remoteController.listConnections",
  remoteControllerSendCommand: "remoteController.sendCommand",
  remoteControllerListCommandRuns: "remoteController.listCommandRuns",
  remoteControllerListDirectory: "remoteController.listDirectory",
  subscribeRemoteControllerEvents: "subscribeRemoteControllerEvents",

  // Traffic Lens
  trafficLensGetTraffic: "trafficLens.getTraffic",
  trafficLensGetTrafficDetail: "trafficLens.getTrafficDetail",
  trafficLensClearTraffic: "trafficLens.clearTraffic",
  trafficLensReplayRequest: "trafficLens.replayRequest",
  trafficLensListFindings: "trafficLens.listFindings",
  trafficLensListRules: "trafficLens.listRules",
  trafficLensUpsertRule: "trafficLens.upsertRule",
  trafficLensDeleteRule: "trafficLens.deleteRule",
  trafficLensListOverrides: "trafficLens.listOverrides",
  trafficLensUpsertOverride: "trafficLens.upsertOverride",
  trafficLensDeleteOverride: "trafficLens.deleteOverride",
  trafficLensListProfiles: "trafficLens.listProfiles",
  trafficLensUpsertProfile: "trafficLens.upsertProfile",
  trafficLensDeleteProfile: "trafficLens.deleteProfile",
  trafficLensListStorageOrigins: "trafficLens.listStorageOrigins",
  trafficLensGetCookieSnapshot: "trafficLens.getCookieSnapshot",
  trafficLensGetLocalStorageSnapshot: "trafficLens.getLocalStorageSnapshot",
  trafficLensListSessionStorageSnapshots: "trafficLens.listSessionStorageSnapshots",
  trafficLensGetSessionStorageSnapshot: "trafficLens.getSessionStorageSnapshot",
  trafficLensUpdateSessionStorageSnapshot: "trafficLens.updateSessionStorageSnapshot",
  trafficLensGetStorageVersions: "trafficLens.getStorageVersions",
  trafficLensClearPersistedOrigin: "trafficLens.clearPersistedOrigin",
  subscribeTrafficLensEvents: "subscribeTrafficLensEvents",

  // Plan Runner
  planRunnerStart: "planRunner.start",
  planRunnerGetStatus: "planRunner.getStatus",
  planRunnerCancel: "planRunner.cancel",
  planRunnerStop: "planRunner.stop",
  planRunnerResume: "planRunner.resume",
  subscribePlanRunnerEvents: "subscribePlanRunnerEvents",
  planRunnerListFeatures: "planRunner.listFeatures",
  planRunnerGetFeaturePlans: "planRunner.getFeaturePlans",
  planRunnerGetFeatureRun: "planRunner.getFeatureRun",
  planRunnerListRuns: "planRunner.listRuns",
  planRunnerGetStepLog: "planRunner.getStepLog",
  planRunnerArchiveFeature: "planRunner.archiveFeature",
  planRunnerUnarchiveFeature: "planRunner.unarchiveFeature",
  planRunnerListArchivedFeatures: "planRunner.listArchivedFeatures",
  planRunnerRenameFeature: "planRunner.renameFeature",
  planRunnerRerunFromFailure: "planRunner.rerunFromFailure",

  // Workflows
  workflowsCreateDraft: "workflows.createDraft",
  workflowsListThread: "workflows.listThread",
  workflowsOpenSource: "workflows.openSource",
  workflowsSyncSource: "workflows.syncSource",
  workflowsValidate: "workflows.validate",
  workflowsArchive: "workflows.archive",
  workflowsRun: "workflows.run",
  workflowsStop: "workflows.stop",
  workflowsRespondToInput: "workflows.respondToInput",
  workflowsGetRun: "workflows.getRun",
  workflowsGetTimeline: "workflows.getTimeline",
  subscribeWorkflowEvents: "subscribeWorkflowEvents",

  // Managed Process
  managedProcessList: "managedProcess.list",
  managedProcessStart: "managedProcess.start",
  managedProcessStop: "managedProcess.stop",
  managedProcessForceKill: "managedProcess.forceKill",
  managedProcessRestart: "managedProcess.restart",
  managedProcessWriteStdin: "managedProcess.writeStdin",
  managedProcessUpsertDefinition: "managedProcess.upsertDefinition",
  managedProcessDeleteDefinition: "managedProcess.deleteDefinition",
  managedProcessSubscribeLog: "managedProcess.subscribeLog",
  managedProcessProposedImports: "managedProcess.proposedImports",

  // Source control
  sourceControlLookupRepository: "sourceControl.lookupRepository",
  sourceControlCloneRepository: "sourceControl.cloneRepository",
  sourceControlPublishRepository: "sourceControl.publishRepository",

  // Source-control stack
  sourceControlStackGetSnapshot: "sourceControl.stack.getSnapshot",
  sourceControlStackCreateEntry: "sourceControl.stack.createEntry",
  sourceControlStackSwitchEntry: "sourceControl.stack.switchEntry",
  sourceControlStackRenameEntry: "sourceControl.stack.renameEntry",
  sourceControlStackDropEntry: "sourceControl.stack.dropEntry",
  sourceControlStackReorderEntries: "sourceControl.stack.reorderEntries",
  sourceControlStackRestack: "sourceControl.stack.restack",
  sourceControlStackSync: "sourceControl.stack.sync",
  sourceControlStackSquashEntry: "sourceControl.stack.squashEntry",
  sourceControlStackSplitEntry: "sourceControl.stack.splitEntry",
  sourceControlStackPublish: "sourceControl.stack.publish",
  sourceControlStackContinueOperation: "sourceControl.stack.continueOperation",
  sourceControlStackAbortOperation: "sourceControl.stack.abortOperation",
  subscribeSourceControlStackEvents: "subscribeSourceControlStackEvents",
} as const;
